'use strict';
let colors = ['red', 'white', 'blue'];
console.log('value of colors[0]:', colors[0]);
console.log('value of colors[1]:', colors[1]);
console.log('value of colors[2]:', colors[2]);
const colorLiteral = `America is ${colors[0]}, ${colors[1]}, and ${colors[2]}.`;
console.log(colorLiteral);
colors[2] = 'green';
const colorLiteral2 = `Mexico is ${colors[0]}, ${colors[1]}, and ${colors[2]}.`;
console.log(colorLiteral2);
console.log('value of colors:', colors);
console.log('typeof colors:', typeof colors);
let students = ['Jesse', 'Celine', 'Rick', 'Ilsa'];
const numberOfStudents = students.length;
console.log('There are', students.length, 'students in the class.');
const lastIndex = numberOfStudents - 1;
const lastStudent = students[lastIndex];
console.log('The last student in the array is', lastStudent, '.');
console.log('value of students:', students);
console.log('typeof students:', typeof students);
