'use strict';
const number = 9200;
const street = 'Irvine Center Drive';
const temp1 = `LearningFuze: ${number} ${street}`;
console.log(temp1);
const firstName = 'Uzair';
const lastName = 'Ashraf';
const age = 25;
const temp2 = `Bio: My name is ${firstName} ${lastName} and I am ${age} years old.`;
console.log(temp2);
const fruit = 'apple';
const item = 'pen';
const applePen = fruit + item;
const temp3 = `I have a ${item}`;
console.log(temp3);
const temp4 = `I have an ${fruit}`;
console.log(temp4);
const temp5 = `${applePen}`;
console.log(temp5);
