'use strict';
let width = 5;
let height = 7;
const area = width * height;
console.log('value of area:', area);
console.log('typeof area:', typeof area);
let bill = 20;
let payment = 50;
const change = payment - bill;
console.log('value of change:', change);
console.log('typeof change:', typeof change);
let quizzes = 84;
let midterm = 75;
let final = 87;
const grade = (quizzes + midterm + final) / 3;
console.log('value of grade:', grade);
console.log('typeof grade:', typeof grade);
let firstName = 'Devin';
let lastName = 'Olesen';
const fullName = firstName + ' ' + lastName;
console.log('value of fullName:', fullName);
console.log('typeof fullName:', typeof fullName);
let pH = 9;
const isAcidic = pH < 7;
console.log('value of isAcidic:', isAcidic);
console.log('typeof isAcidic:', typeof isAcidic);
let headCount = 277;
const isSparta = headCount === 300;
console.log('value of isSparta:', isSparta);
console.log('typeof isSparta:', typeof isSparta);
let motto = fullName;
motto += ' is the GOAT';
console.log('value of motto:', motto);
console.log('typeof motto:', typeof motto);
